package test;

import database.CandyDB;
import connection.DataAccessException;
import model.Candy;
import org.junit.jupiter.api.*;

import java.sql.Date;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class CandyDBTest {

    private static CandyDB candyDB;
    private static Candy testCandy;
    private static int testCandyId; // <-- store generated ID

    @BeforeAll
    static void setup() throws DataAccessException {
        candyDB = new CandyDB();
        // ID is generated by the DB
        testCandy = new Candy(0, "lollipop", 10, 1, 100, new Date(System.currentTimeMillis()), 0, "TestCandy");
        Candy insertedCandy = candyDB.insert(testCandy);
        testCandyId = insertedCandy.getCandyID(); // capture the generated ID
        testCandy.setCandyID(testCandyId);
    }

    @Test
    @Order(1)
    void testFindById() throws DataAccessException {
        Candy candy = candyDB.findById(testCandyId); // use generated ID
        assertNotNull(candy);
        assertEquals("TestCandy", candy.getName());
    }

    @Test
    @Order(2)
    void testUpdate() throws DataAccessException {
        testCandy.setPrice(15);
        candyDB.update(testCandy);
        Candy candy = candyDB.findById(testCandyId);
        assertEquals(15, candy.getPrice());
    }

    @Test
    @Order(3)
    void testGetAllCandy() throws DataAccessException {
        List<Candy> allCandy = candyDB.getAllCandy();
        assertTrue(allCandy.size() > 0);
        assertTrue(allCandy.stream().anyMatch(c -> c.getCandyID() == testCandyId));
    }

    @Test
    @Order(4)
    void testGetCandyByType() throws DataAccessException {
        List<Candy> lollipops = candyDB.getCandyByType("lollipop");
        assertTrue(lollipops.stream().anyMatch(c -> c.getCandyID() == testCandyId));
    }

    @Test
    @Order(5)
    void testGetLowStockCandy() throws DataAccessException {
        List<Candy> lowStock = candyDB.getLowStockCandy();
        assertTrue(lowStock.stream().anyMatch(c -> c.getCandyID() == testCandyId));
    }

    @AfterAll
    static void cleanup() throws DataAccessException {
        candyDB.delete(testCandyId); // remove the test candy
    }
}
